version: '3.8'

services:
  dev:
    container_name: movie_container
    image: movie_container:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - 4007:4007
      # - "${PORT}:${PORT}"
    networks:
      - netguru-network
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    restart: unless-stopped

#Docker Networks
networks:
  # All container connect in a network
  netguru-network:
    driver: bridge
# save (persist) data
volumes:
  node_modules:
  db_data: {}
  es_data: {}
