name: movie test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./netguru-recruitment-task
    steps:
      - name: CHECK-OUT GIT REPOSITORY
        uses: actions/checkout@v2

      - name: INSTALL PROJECT DEPENDENCIES (NPM)
        run: npm install

      - name: UNIT TEST (JEST)
        run: npm run test