name: movie test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# jobs:
#   test: # this is the name of the job
#     runs-on: ubuntu-latest

#     steps:
#       - name: Run Tests
#         # working-directory: ../../netguru-recruitment-task
#         run: |
#           npm install
#           npm run test

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./netguru-recruitment-task
    # strategy:
    #   matrix:
    #     node-version: [14.x]
    #     architecture: [x64]
    steps:
      - name: CHECK-OUT GIT REPOSITORY
        uses: actions/checkout@v2

      # - name: USE NODEJS ${{ matrix.node-version }} - ${{ matrix.architecture }}
      #   uses: actions/setup-node@v2

      - name: INSTALL PROJECT DEPENDENCIES (NPM)
        run: npm install

      - name: UNIT TEST (JEST)
        run: npm run test